services:
  redis:
    image: redis:7-alpine
    container_name: orders-redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  redis-data: